# Generated by Django 4.1.2 on 2022-10-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pageone", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="ContactForm",),
    ]
